### PR TITLE
Add prototypes & other fixes to address `gcc -Wall' warnings

### PR DESCRIPTION
**Pull request by tkchia**
After fixing the sources to build with `ia16-elf-gcc`, I
have also rebuilt and updated the `TINYASM.EXE` binary using
DeSmet C (3.1h).

### CODE REVIEW

**Comment by nanochess** [comment]
I'm impressed that you managed to remove the obscure DeSmet C warnings! Thanks!

**Comment by nanochess** [comment]
BTW your executable didn't worked with the provided test.bat file. I recompiled it again locally.

**Comment by tkchia** [comment]
Hello @nanochess,

> I'm impressed that you managed to remove the obscure DeSmet C warnings! Thanks!

Thank you!  I guess the real credit goes to GCC --- it is definitely a lot more bloated than DeSmet C, but its diagnostic messages are a bit clearer. :)

**Comment by tkchia** [comment]
> BTW your executable didn't worked with the provided test.bat file. I recompiled it again locally.

I will try to look into why the executable produced on my end is not working properly.  Thank you!

**Comment by tkchia** [comment]
Hello @nanochess,

It turns out that I had omitted to apply the [3.1N patches](http://www.desmet-c.com/ver_31n.shtml) to DeSmet C.  Thank you!

**Pull request merged**
